# Generated by Django 5.2.7 on 2025-10-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['key'], name='core_idempo_key_145b58_idx'),
        ),
    ]
